import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

const SITE_URL = "https://project.mayankiitj.in";
const SITE_NAME = "Virtual Mouse";
const SITE_TITLE = "Virtual Mouse — AI-Powered Hand Gesture Control | Mayank Sharma";
const SITE_DESC =
  "Control your computer using hand gestures with real-time computer vision. Open-source AI-powered Virtual Mouse using MediaPipe, OpenCV, and Python — no hardware required, just a webcam.";

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
  themeColor: [
    { media: "(prefers-color-scheme: dark)", color: "#050505" },
    { media: "(prefers-color-scheme: light)", color: "#050505" },
  ],
};

export const metadata: Metadata = {
  metadataBase: new URL(SITE_URL),

  // ─── Core ────────────────────────────────────────
  title: {
    default: SITE_TITLE,
    template: `%s | ${SITE_NAME}`,
  },
  description: SITE_DESC,
  applicationName: SITE_NAME,
  category: "Technology",
  keywords: [
    "virtual mouse",
    "hand gesture control",
    "computer vision",
    "gesture recognition",
    "MediaPipe",
    "OpenCV",
    "Python",
    "AI",
    "machine learning",
    "human-computer interaction",
    "HCI",
    "touchless interface",
    "accessibility",
    "hand tracking",
    "webcam gesture",
    "cursor control",
    "Mayank Sharma",
    "open source",
  ],
  authors: [
    { name: "Mayank Sharma", url: "https://mayyanks.app" },
    { name: "Mayank Sharma", url: "https://mayankiitj.in" },
  ],
  creator: "Mayank Sharma",
  publisher: "Mayank Sharma",
  generator: "Next.js",

  // ─── Crawling ────────────────────────────────────
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      noimageindex: false,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  // ─── Canonical & Alternates ──────────────────────
  alternates: {
    canonical: SITE_URL,
  },

  // ─── Open Graph ──────────────────────────────────
  openGraph: {
    title: SITE_TITLE,
    description: SITE_DESC,
    type: "website",
    siteName: SITE_NAME,
    locale: "en_US",
    url: SITE_URL,
    // OG image auto-generated by src/app/opengraph-image.tsx
  },

  // ─── Twitter / X ─────────────────────────────────
  twitter: {
    card: "summary_large_image",
    title: SITE_TITLE,
    description: SITE_DESC,
    creator: "@mayyankks",
    site: "@mayyankks",
    // Twitter image auto-generated by src/app/twitter-image.tsx
  },

  // ─── Icons & Manifest ────────────────────────────
  manifest: "/manifest.json",
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    apple: [
      { url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" },
    ],
  },

  // ─── Verification (add IDs when available) ───────
  // verification: {
  //   google: "your-google-verification-id",
  //   yandex: "your-yandex-verification-id",
  // },

  // ─── Other ───────────────────────────────────────
  other: {
    "msapplication-TileColor": "#050505",
    "apple-mobile-web-app-title": SITE_NAME,
  },
};

// ─── JSON-LD Structured Data ─────────────────────
const jsonLd = {
  "@context": "https://schema.org",
  "@graph": [
    {
      "@type": "WebSite",
      "@id": `${SITE_URL}/#website`,
      url: SITE_URL,
      name: SITE_NAME,
      description: SITE_DESC,
      publisher: { "@id": `${SITE_URL}/#person` },
      inLanguage: "en-US",
    },
    {
      "@type": "WebPage",
      "@id": `${SITE_URL}/#webpage`,
      url: SITE_URL,
      name: SITE_TITLE,
      description: SITE_DESC,
      isPartOf: { "@id": `${SITE_URL}/#website` },
      about: { "@id": `${SITE_URL}/#software` },
      inLanguage: "en-US",
    },
    {
      "@type": "SoftwareApplication",
      "@id": `${SITE_URL}/#software`,
      name: SITE_NAME,
      description: SITE_DESC,
      applicationCategory: "Utility",
      operatingSystem: "Windows, macOS, Linux",
      offers: {
        "@type": "Offer",
        price: "0",
        priceCurrency: "USD",
      },
      author: { "@id": `${SITE_URL}/#person` },
      url: "https://github.com/Mayank-iitj/virtualmouse",
      downloadUrl: "https://github.com/Mayank-iitj/virtualmouse",
      softwareVersion: "1.0",
      featureList: [
        "Real-time hand gesture recognition",
        "AI-powered cursor control",
        "Click and scroll gestures",
        "MediaPipe hand tracking",
        "No additional hardware required",
      ],
    },
    {
      "@type": "Person",
      "@id": `${SITE_URL}/#person`,
      name: "Mayank Sharma",
      url: "https://mayyanks.app",
      sameAs: [
        "https://github.com/Mayank-iitj",
        "https://linkedin.com/in/mayankiitj",
        "https://instagram.com/mayyanks",
        "https://x.com/mayyankks",
        "https://mayankiitj.in",
      ],
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="ltr" className="dark">
      <head>
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <link rel="canonical" href={SITE_URL} />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        {children}
      </body>
    </html>
  );
}
